profile: dev

server_host: 0.0.0.0
server_rest_port: 5000


db:
  host: 127.0.0.1
  port: 5432
  database: hack_server
  username: postgres
  password: postgres
  migrations: ./migrations

s3:
  url: http://94.154.128.76:9000
  login: minio-root
  password: JustOleg1!
  bucket: user-data

panda:
  bootstrap_servers:
    - 94.154.128.76:9001:19092
  security_protocol: SASL_SSL
  sasl_mechanism: SCRAM-SHA-256
  sasl_plain_username: panda-client
  sasl_plain_password: p9SCJD0meTUk9iiUEW2IzvxwMGN5go

logging:
  app_name: cc-gate
  graylog:
    enabled: false
    host: localhost
    port: 12201
    udp: true
  console:
    enabled: true
  root_level: INFO
  levels:
    httpx: WARN
    openai: WARN
    uvicorn.access: WARN
    VastController: DEBUG
